name: isTTY

on:
  push:

jobs:
  tty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v6
      - run: npm ci --no-audit
      - name: Passing, no color
        run: npx elm-test tests/Passing.elm
      - name: Passing, color
        run: npx elm-test --color tests/Passing.elm
      - name: Failing, no color
        run: npx elm-test tests/Failing.elm
      - name: Failing, color
        run: npx elm-test --color tests/Failing.elm
