name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [synchronize, reopened, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run workflow
        run: |
          node -p "Oh yes!"
