name: Merged

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: |
        node --version
        git config user.name 'PowerCleanup'
        git config user.email '<>'
        git switch -c test-auto-pr
        git rm foobar1.txt
        git commit -m 'Auto remove'
        git push --set-upstream --force
        gh pr create --title 'Auto remove' --body 'Test text'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
