name: Merged

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: node --version
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
