name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]

jobs:
  build:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14"

      - name: Run workflow
        run: |
          node index.js
