name: Merged

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - run: |
        git diff --name-status HEAD^ HEAD
        if git diff --name-status HEAD^ HEAD | grep '^A'; then
          gh pr comment $PR --body "✅ PR added foobar* file!"
        else
          gh pr comment $PR --body "❌ No added foobar* files."
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR: ${{ github.event.pull_request.number }}
